openapi: 3.0.0
info:
  title: otaQku Tasks API
  version: 1.0.0
  description: Backend Engineer Technical Test

servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://otaqku-api.hawari.dev
    description: Production server

components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
  responses:
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Invalid token"
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "You're not allowed to access this resource"
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Resource not found"
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Internal Server Error"

paths:
  /:
    get:
      description: Public home endpoint
      tags: [Public]
      responses:
        200:
          description: Returns welcome message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Welcome to otaQku tasks management API
        500:
          $ref: '#/components/responses/InternalServerError'